name: traefik-ingress
version: 0.2
appVersion: 1.5.4
description: A traefik ingress controller
icon: https://d33wubrfki0l68.cloudfront.net/e29410f43273a18d40e1bd6e41641f5afdfc8057/eb7ca/traefik.logo.png
keywords:
  - ingress
  - traefik
sources:
  - https://github.com/adyromantika/fun-with-kubernetes
maintainers:
  - name: adyromantika
engine: gotpl
